### PR TITLE
Simplify imv-folder script and rename it to imv-dir

### PR DESCRIPTION
**Pull request by begss**
This makes it more portable by removing bash dependency and not using
GNU-specific 'sort' syntax. Also this fixes issue with selected image
not being displayed first at least for me.

### CODE REVIEW

**Comment by gnull** [comment]
Doesn't the `$1` that you pass to grep get interpreped as a regex, not a string? What happens if someone sends me a file named `.*` and I open it in `imv-folder`? (Could one pwn a user in some other way through a grep regex?)

**Comment by gnull** [comment]
How about doing `grep -Fx "$1"` instead? This one should match lines exactly and not interpret anything as a regex.

(I haven't tested it, commenting from my phone.)

**Review by gnull — APPROVED** [review]

**Comment by begss** [comment]
On Sat Sep 18, 2021 at 4:54 AM MSK, Ivan Oleynikov wrote:
> Doesn't the `$1` that you pass to grep get interpreped as a regex, not a
> string? What happens if someone sends me a file named `.*` and I open it
> in `imv-folder`? (Could one pwn a user in some other way through a grep
> regex?)
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/eXeC64/imv/pull/349#issuecomment-922159575

Thanks, good catch, fixed.

**Comment by begss** [comment]
*couldn't log in to github for some time due to problems either w/ my email provider or github email service*

**Comment by eXeC64** [comment]
Thanks

**Pull request merged**
