### PR TITLE
use inih as subproject

### PR DESCRIPTION
**Pull request by stephanlachnit**
I added a `meson.build` file for inih, meaning it is now exposed via pkg-config, so one can now link at it instead of copying the source files by hand.
However, this is so recent that it probably will take some time until distro can ship it. But it is possible to add inih as a fallback in meson, so that everyone can build it as before.
If you don't know about subprojects in meson, here's the [reference](https://mesonbuild.com/Subprojects.html#update-subprojects). It uses git submodules, which don't update themselves, so once r48 of inih is released I would checkout the submodule at that commit and leave it there.

### CODE REVIEW

**Comment by stephanlachnit** [comment]
Rebased against inih r48.

**Comment by alebastr** [comment]
I'm curious about the preference of submodule over wrap file. wrap is a native meson feature and does not require a git tree to build.

Both options are not very helpful for distro packaging though. Most binary distributions (i.e. rpm or deb based) forbid network access from build chroots making it impossible to fetch either submodule or wrap file. For my Fedora package I had to add find_library lookup:
```
dep_inih = dependency('inih', required : false, fallback : ['inih', 'inih_dep'])
if not dep_inih.found()
    # fallback for inih < 48
    dep_inih = cc.find_library('inih', required : true)
endif
```

**Comment by stephanlachnit** [comment]
meson will search dependency inih in pkg-conifg, and then only downloads inih as a fallback if it's not found.
Fedora has inih r36 which has no pkg-config entry for inih.
Debian will have r48, don't know about Fedora, so I guess the imv maintainer has to update it? Should be easy enough with though.

**Comment by alebastr** [comment]
It doesn't download inih though.
```
Run-time dependency inih found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency inih

meson.build:40:0: ERROR: Subproject exists but has no meson.build file
```

**Comment by stephanlachnit** [comment]
> It doesn't download inih though.

Are you sure you checked out properly on my branch while you were connected to the internet? It does it for me, tested from a clean clone: 
```bash
git clone https://github.com/stephanlachnit/imv.git
cd imv
git checkout upstream-inih
meson builddir
```

Anyway, I switched to a wrap file, since it's less of a hassle.

**Comment by stephanlachnit** [comment]
@eXeC64 friendly ping

**Comment by stephanlachnit** [comment]
@eXeC64 just rebased and took the latest Wrap from Meson's [Wrap DB](https://wrapdb.mesonbuild.com/). I also updated the CIs to use the system installation of inih, which is now widely available: https://repology.org/project/inih/versions (r48 is the first version with a pkg-config file, which is available in Arch, Debian Buster Backports, Fedora 32 Updates and Ubuntu 20.04).

And even if it isn't available (as in FreeBSD afaik), it still works thanks to the fallback Wrap.

Ubuntu CI failing is not because of this PR, see #286.

**Comment by eXeC64** [comment]
Thanks! Sorry this took so long to merge

**Pull request merged**
