### PR TITLE
[WIP] inotify support

### PR DESCRIPTION
**Pull request by rien333**
_Disclaimer_: I rarely program anymore, so I am not sure wether my code is any good. Feel free to just discard this PR if you feel like it needs too much feedback. That said, I do have some time to potentially improve things this week.

This PR fixes https://github.com/eXeC64/imv/issues/162, but is probably more of a work in progress (see above).

# Approach #

I mostly just incorporated the old, now removed inotify code within the modern code base. The old inotify code failed to compile on non-linux systems (see [#67](https://github.com/eXeC64/imv/issues/67)). To solve this,  all inotify related code is now wrapped in `#ifdef __linux__` statements (as discussed in https://github.com/eXeC64/imv/issues/162, but see the final section). I tested this PR on FreeBSD (12.1), and it builds and runs fine there. 

# Results #

Image reloading is noticably faster when imv is compiled with  inotify support. Initially,  I suspected the speed-up could be the result of me lowering the delay in the main loop (i.e. the [timeout  variable](https://github.com/eXeC64/imv/blob/c9b8ec89cc9d158b0d5f637ea3a29ae311f85a89/src/imv.c#L1015) in `imv.c`). However, my suspicion proved wrong, and without the inotify code in place, there seemed to be no significant difference in image reloading time when comparing `double timeout = 0.1` versus `double timeout = 1.0`.

On the topic of delays: I noticed that inotify didn't provide a lot of speed benefits when using the current main loop delay of 1.0s. Additionally, I noticed that the version of imv that still supported inotify, used a delay of only 10ms. Therefore, I lowered the current delay of 1s to 100ms on linux systems. Please do tell me if you think another value would be appropiate, or if you would suggest a totally different approach. 

On my intel i7, this PR ~increases CPU usage by about 0.1%, averaged over a long time period~. (never mind, CPU usage need some more investigation — there might even be a CPU usage decrease)

# Things I'm unsure about #

- I'm not very fond of having `#ifdef __linux__` statements all over. If you prefer, it might be a better idea to move some functions to linux-specific files (e.g. `reload_inotify`,  and `reload` for non-linux systems), and then let the Makefile decide the appropiate files. `sxiv` seems to have done something similair with [autoreload_inotify.c](https://github.com/muennich/sxiv/blob/1613b42411788810d73252ac86952b3e66c866ba/autoreload_inotify.c) and [inotify_nop.c](https://github.com/muennich/sxiv/blob/1613b42411788810d73252ac86952b3e66c866ba/autoreload_nop.c). An approach like this was also discussed in https://github.com/eXeC64/imv/issues/67, where it was suggested to implement a BSD alternative as well (sounds fun, but could maybe take me a while). On the other hand, spreading stuff out over multiple files might require a lot of refactoring.
- When imv still used inotify, the following approach was used:

```c
// In imv.c 
while (imv_navigator_poll_changed(imv->navigator) || imv_reload_changed(imv->reload)) {
    ...
}
```

However, I moved the second condition upwards, because otherwhise the while loop of the above snippet would evaluate to true twice in a row:

```c
// In imv.c 
if (imv_reload_changed(imv->reload)) {
  imv_navigator_set_changed(imv->navigator, 1);
}

while (imv_navigator_poll_changed(imv->navigator)) {
...
}
```

___

My compliments on the readability of your code btw, very easy to understand and navigate. I tried to do a similar small fix in C for another program, and I didn't get very far.

### CODE REVIEW

**Comment by rien333** [comment]
Been using this for a few days now and, as far as I can see, it works good. Image reloading speed is definitely improved, and monitoring with htop shows (virtually) no extra cpu usage (it seems stagnant on 0.0%).

**Comment by rien333** [comment]
@eXeC64 FIY, the fact that I've called this a "WIP" is because I anticipate that you have some feedback, not because I'm still (actively) working on it.

**Comment by rien333** [comment]
Thanks for the feedback!

> The idea behind `inotify` is to avoid checking whether file has changed in every second thus increasing response time and decreasing CPU usage to -0.0%. You basically kill this by setting `timeout = 0.1`. It's 10x worse than it was before. Please, see `inotify(7)` for reasonable usage.

I understood this aspect of inotify, but was unsure of the implementation. I'll reread the manual and see if I can come up with something else. 

What I think might be happening is that I'm either confused or misunderstood something about the previous implementation of inotify in imv. At first glance, the [previous approach](https://github.com/eXeC64/imv/blob/d0b041f17c34fc36fc8121cfe23e2da2b79cf4fa/src/main.c#L562) seem really similar to this PR: 

```c
/* the main loop */
int quit = 0;
while(!quit) {
    ...
    /* use inotify to check if the  underlying file changed  */
    if(imv_navigator_poll_changed(&nav) || imv_reload_changed(&reload)) {
      const char *current_path = imv_navigator_selection(&nav);
      ...
    }
    ...
    /* sleep for 10ms  */
    SDL_Delay(10);
}
```

My best guess would be that the drawing code is really different in  newer imv versions (SDL doesn't seem to be used directly), and that the `SDL_Delay` call above serves a completely different purpose than the (pseudo-)equivalent timeout delay in the current implementation. 

I don't have time to work on this in the coming week (although I'll have some time after that), so anyone should feel free to implement this if the can do better.

**Comment by zsugabubus** [comment]
I don't think I can modify your pull request (and it wouldn't be fair to open a new one), but I'm gladly help you if you have stucked.

Here is how I would do:
If `rld->fd != -1` `poll()` for it with default timeout `-1` (wake up only if an event occurred) inside
https://github.com/eXeC64/imv/blob/c9b8ec89cc9d158b0d5f637ea3a29ae311f85a89/src/window.h#L83
If poll says that it's readable (inotify wants notify us), you have to `read()` it until `EAGAIN` and check if any event was `IN_CLOSE_WRITE`.

**Comment by rien333** [comment]
That makes more sense! Thanks.

**Comment by zsugabubus** [comment]
Could you make any progress since?

###### I absolutely don't want to hurry but if you say you didn't/won't have time in the near future I'm gladly try implementing it too.

**Comment by rien333** [comment]
Yeah, someone else can totally take over. I won't have time for this until February.

**Comment by zsugabubus** [comment]
> Just make sure this works on BSDs/non linux systems, which was the reason inotify support was removed in the first place.

No, I don't think so. 😠

“Non-Linux” guys had the chance to implement it in c609696 with `kqueue` (or anything they want I don't know–or if they don't have alternative get rid of their s*** system) but they just go with busy `stat`ing the filesystem. If it's okay for them I don't mind but consuming everybody's CPU time on Linux superfluously and ruining their experience in unacceptable. If they couldn't put the Linux-specific part into a “f*cking big `#ifdef`”, I surely won't kill time implementing it for them.

But `stat` works for them now too 😆... I won't change that part... as they did.

I don't really understand how this commit could get accepted at all.

**Comment by rien333** [comment]
Ah whoops, I meant that you should make sure that whatever you do, make sure `imv` as a whole doesn't break on BSD. I wasn't suggesting that you should implement a similar functionality with `kqueue`, in addition to inotify. I understand that as a linux user, you don't care about learning about and implementing a whole bunch of extra stuff (anyways, there are like 2 BSD users of imv anyway 😉, just don't hurt them)

**Comment by zsugabubus** [comment]
Of course. I will try not to remove things carelessly. The main issue wouldn't be the learning, but the testing. I wouldn't like to commit something that I never ever tried.

> anyways, there are like 2 BSD users of imv anyway 😉, just don't hurt them

Then it even makes less sense why they dropped `inotify`!?!

---

@eXeC64, I run into a tiny issue:

* Checking changes by `stat` happens at `imv_navigator_poll_changed` in the while loop.
*  Polling for changes happens at the display backend specific wl or x11 `imv_window_wait_for_event`. ((`imv_window_wait_for_event` should be renamed to `imv_wait_for_event` because an event can arrive from other sources.))

Logically the reload structure should be attached to navigator because this is what cares about files, but because polling happens at the window, it should be inside `struct window`. However, navigator and window don't know each other, they are only part of `struct imv`, so it's impossible to solve. Previously there was a global reload object, but it's very hacky. What do you think?

**Comment by rien333** [comment]
BTW, does your current inotify branch work yet @zsugabubus? I could spare you some time by testing  it on BSD (don't think you have implemented support yet though), although setting up a VM yourself is pretty easy. Furthermore, I would also like  to test/use it on my daily linux setup (as ExeC64 is not frequently active, I'm okay with running your fork for a bit).

**Comment by zsugabubus** [comment]
No, not yet working. I stopped because the reasons mentioned above: I couldn't logically arrange the code. Either a lot's of things should be rewritten or just go and use a global object (that tracks the current state of inotify) that you place randomly somewhere. I didn't want to make things worse, that's why I expected some hints from eXeC64.

**Comment by eXeC64** [comment]
Ah sorry, I've not had much time lately to follow up on PRs for imv, I got married last week. I'll try and catch up soon.

**Comment by rien333** [comment]
@eXeC64 
> Either a lot's of things should be rewritten or just go and use a global object (that tracks the current state of inotify) that you place randomly somewhere. I didn't want to make things worse, that's why I expected some hints from eXeC64.

Any notes on how to proceed?

**Comment by rien333** [comment]
Closing this, mostly because my solution is not that good anyway.

**Pull request closed without merging**
