### PR TITLE
Issue #189 don't fail to display image if its not a vaild path

### PR DESCRIPTION
**Pull request by rehaby**

### CODE REVIEW

**Comment by escondida** [comment]
I just tested this patch, and I concur that it works. Is there anything blocking this getting merged (and perhaps a new point release so distributions could use it)?

**Comment by eXeC64** [comment]
Thanks for the patch. I'm applying this to master.

Sorry about the delay - I've been busy moving house.

**Comment by eXeC64** [comment]
Actually, I had to un-apply this. With this applied running `imv ~/photos` doesn't pick up the contents of that directory anymore. Can you look into that please?

**Comment by escondida** [comment]
Iiinteresting. I may have some time to look at it later, but just in case...rehaby, as original submitter: thoughts?

**Comment by eXeC64** [comment]
Resolved by #208

**Pull request closed without merging**
