### PR TITLE
sxiv-like 'start at' option

### PR DESCRIPTION
**Pull request by autrimpo**
Implements #21.
Manpage is not changed, as I noticed it differs from the help text (is that intentional?).

### CODE REVIEW

**Comment by eXeC64** [comment]
The manpage ought to be kept up to date. Any differences are a mistake (probably sloppyness on my part).

Instead of calling `imv_navigator_next_path` repeatedly, I think it would be better if you added a new function to navigator, something like `void imv_navigator_set_path(int path)`. All it needs to do is a bounds-check of the input, leave the `last_move_direction` value unchanged, and if needed set the `changed` flag. It'd be cleaner, and save a few processor cycles.

Lastly, in the option parsing code you have 4 space indentation. Could you change it to 2 spaces please?

Other than that, this looks good to me. Thanks.

**Comment by autrimpo** [comment]
Sure, I'll do that.

**Comment by autrimpo** [comment]
I assume bound check against nav->num_paths. What should be the behaviour if it's greater? Do nothing or %num_paths and continue?

**Comment by eXeC64** [comment]
It probably makes more sense to do nothing in that case, same for a negative input. If you like, make the function return an `int` with `0` denoting success and `1` failure.

**Comment by autrimpo** [comment]
That sounds reasonable.

**Comment by autrimpo** [comment]
Should be ok now, I'll rewrite the man page (descriptions of flags are different, options vs flags and such) and submit that as a separate PR.

**Comment by eXeC64** [comment]
Sounds good, thanks.

**Pull request merged**
