### PR TITLE
Add slideshow option.

### LINKED ISSUE #45: Slideshow option.
Is there interest in adding a slideshow option?

I propose something super simple like a command line option `-s` that expects an integer argument and just skips to the next image after the specified number of seconds.

Thoughts?

If there is interest, I'd go ahead and try to come up with a solution.

### PR DESCRIPTION
**Pull request by whatevsz**
Ok, I gave it a go and implemented the slideshow option. Should support all features you requested:

* `-t [time]` option to set how long to show each image for
* `t` key binding increases display time by 1 second
* `T` key binding decreases display time by 1 second
* If non-zero, the time left and display time should be shown in the overlay and window title in the form `[display-time-so-far/display-time]`
* A display time of `0` indicates the slideshow is not active

I wasn't sure how to force a redraw of the image (needed because window title and overlay have to be updated every second for the "countdown"). I don't think settings `view->redraw` directly is the best course of action.

Any suggestions/improvements/requests? Has been some time since I last touched a C codebase, so please don't be too harsh ;)

Resolves #45

### CODE REVIEW

**Comment by eXeC64** [comment]
Thanks for the patch, it looks good. I've just got a couple of suggestions for it.

* `overlay_surf` and `overlay_tex` are being leaked each redraw. [This](https://github.com/whatevsz/imv/blob/slideshow/src/main.c#L422-L430) section needs to be moved over with the overlay recreation. Your patch left it behind it seems.
* Currently the overlay goes from `[0/3 s]` to `[2/3 s]`, would it be more aesthetically pleasing to go from `[1/3s]` to `[3/3s]`? i.e. drop the space and count from 1 to n.
* The new option is documented in the usage example, but the new hotkeys aren't. Please add `[-t SECONDS]` to the usage summary on line 52 as well.
* Please document the new option and binds in the manpage too.

I agree about `view->redraw`. Refactoring the redrawing logic is something I'm planning on doing at some point. At the moment I'm prioritising getting the last few key features in and improving the quality of the codebase as much as possible.

**Comment by whatevsz** [comment]
Ok, I implemented the changes you requested. I agree that counting from 1->n instead of 0->(n-1) is cleaner. I'm not that good at writing docs (not a native speaker), so if you want to reword it let me know.

**Comment by eXeC64** [comment]
That's fine. Thanks. Only one small change I'd make at this point `[-t SECONDS]` in manpage's summary, but I'll just merge now and add that quickly myself.

**Comment by whatevsz** [comment]
Whoops, forgot that. Thank you!

**Pull request merged**
